[phases.setup]
aptPkgs = ["sqlite3"]

[phases.install]
cmds = ["bun install", "composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "bun run build",
    "mkdir -p storage/database",
    "chmod -R 775 storage",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
    "php artisan octane:install --server=frankenphp"
]

[start]
cmd = "php artisan octane:start --host=0.0.0.0 --port=$PORT"

[variables]
NODE_ENV = "production"
